### ISSUE TITLE
Create WebAPI

### ISSUE THREAD

**Issue by Claiyc** [VisualGameData/VIGAD-API#6]
# Issue description
*Describe your issue in detail here*
Create a seperate REST api application that supports the session system by distributing data across clients.

# Subissues

- [x] VisualGameData/VIGAD-API#1 
- [x] VisualGameData/VIGAD-API#2 
- [x] VisualGameData/VIGAD-API#3 
- [x] VisualGameData/VIGAD-API#4 
- [x] VisualGameData/VIGAD-API#5 
- [x] #7 

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
~~- [ ] the issue is assigned to the current sprint~~
~~- [ ] the issue is estimated~~
- [x] a meaningful title has been set
- [x] the issue is described in detail
